# Generated by Django 5.2.8 on 2025-11-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padre',
            name='rut',
        ),
        migrations.AddField(
            model_name='padre',
            name='contraseña',
            field=models.CharField(default='12345', max_length=20),
        ),
    ]
