# Generated by Django 5.2.8 on 2025-11-25 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_padre_rut_padre_contraseña'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField(default=0)),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='usuarios.padre')),
            ],
        ),
    ]
