# Generated by Django 5.2.8 on 2025-11-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_hijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='padre',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
