# Generated by Django 5.2.8 on 2025-12-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_padre_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hijo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
